### ISSUE TITLE
【BUG】switch命令缺陷

### ISSUE THREAD

**Issue by powerAn2020** [Asterisk4Magisk/XrayHelper#13]
1. xray-core 下使用xrayhelper switch 切换节点时生成的文件中streamSettings.tcpSettings缺失，导致无法正常联网
2. xrayhelper switch 命令列表里中文没转换完全
![image](https://github.com/Asterisk4Magisk/XrayHelper/assets/25736019/6f2540af-3350-4df7-a7bb-34fe00a25ee9)

**Comment by whalechoi** [comment]
提供一下有问题的vmess shareurl
cj1369636717@gmail.com

**Comment by whalechoi** [comment]
试试这个 https://github.com/Asterisk4Magisk/XrayHelper/actions/runs/9111487230

**Comment by powerAn2020** [comment]
两项均正常
