### ISSUE TITLE
大佬，安卓11 miui遇到一个问题，使用命令启动不了xray-core

### ISSUE THREAD

**Issue by lovebai** [Asterisk4Magisk/XrayHelper#16]
magisk 安装好模块之后 使用命令 `xrayhelper service start` 启动不了xray 内核，命令提示 ：
```
INFO : service: core is running, pid is 23094
```
core.pid 文件也已创建成功，但是通过ps -ef 和scene 查不到服务进程，重启手机可启动，在magisk模块中点击开关也可启动，但是使用命令 `xrayhelper service start` 不能启动服务。

**Comment by lovebai** [comment]
> 使用命令启动后core的进程立马就挂了？

直接就没启动core

**Comment by whalechoi** [comment]
error.log里面没东西是吧？

**Comment by whalechoi** [comment]
试试这个 https://github.com/Asterisk4Magisk/XrayHelper/actions/runs/9257510278

**Comment by lovebai** [comment]
感谢，老哥，用来您build的版本可以正常启动了
![IMG_20240530_103732](https://github.com/Asterisk4Magisk/XrayHelper/assets/42148495/2a555bc0-859e-43ef-ade1-34c7c5fea10e)
