### ISSUE TITLE
how to disable auto "prettify" configuration

### ISSUE THREAD

**Issue by adiprasetya** [Asterisk4Magisk/XrayHelper#2]
how to disable it? it seems the configuration is automatically sorted alphabetically. this makes my configuration sucks, and unreadable.

**Comment by whalechoi** [comment]
next version will add an option to disable auto change dns strategy, it can solve this

**Comment by adiprasetya** [comment]
thanks for the response. i will waiting for the next version release.

**Comment by whalechoi** [comment]
commit [990dbd98ea95ab550357b4433c914d5184eb75de](https://github.com/Asterisk4Magisk/XrayHelper/actions/runs/5992416799)

**Comment by adiprasetya** [comment]
already test it, it still same. i disable the autoDNSStrategy, not working. it still sorted the config alphabetically.

**Comment by whalechoi** [comment]
clash core need remove clash.template

**Comment by adiprasetya** [comment]
okay, ill try it.

**Comment by adiprasetya** [comment]
okay, tested. working, thanks. this issues can be closed as solved.
